### ISSUE TITLE
Not working with IdentityServer4 v.2.3.0.0

### ISSUE THREAD

**Issue by deka** [Nordes/IdentityServer4.LdapExtension#18]

**Comment by Nordes** [comment]
@deka  please provide more details.

**Comment by deka** [comment]
Hi,
With nuget IdentityServer4 v2.3 and IdentityServer4.LdapExtension v2.0

Compilation fail when i try to add : 
  .AddLdapUsers<ActiveDirectoryAppUser>(Configuration.GetSection("MyConfigurationSection"), UserStore.InMemory);

Error message : 
The type 'IIdentityServerBuilder' is defined in an assembly that is not referenced. You must add a reference to assembly 'IdentityServer4, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null'

**Comment by Nordes** [comment]
The solution is to simply clone the project, update the packages, rebuild and it works.

**Comment by Nordes** [comment]
This will be part of the next release.
