### ISSUE TITLE
Is this extension able to create users and manage roles in the Active Directory ?

### ISSUE THREAD

**Issue by Bogatinovski** [Nordes/IdentityServer4.LdapExtension#21]
Hi,
Is it possible to use this extension to turn my IdentityServer into an ActiveDirectory ? By using the AspNetCore.Identity library in .NET Core my website users will be stored in SQL server. 
I want to be able to store the users and their roles and permissions in an ActiveDirectory. Is it possible with this extension ?

**Comment by jronnen7** [comment]
There is no direct interface that I have found, this is designed to act as an identity server not a user management server.  After looking through the code, I did find the package used to search ldap, using the Novell.Directory.Ldap.NetStandard package, you can easily connect and manage users / groups.
