### ISSUE TITLE
Is this library support Linux?

### ISSUE THREAD

**Issue by maordavidov** [Nordes/IdentityServer4.LdapExtension#23]
Hello,

This library use Windows only libraries or it support Linux?

**Comment by Nordes** [comment]
Hi,

Yes, I actually use it in my pet project running all in docker. I also have an ubuntu server where I deployed it and I had no issue.

A way to configure for testing for example https://blog.honosoft.com/2018/06/18/ldap-identity-server-series-%E3%83%BC-part-i-%E3%83%BC-openldap-on-docker-container/

I use the Novel library which works in windows and linux. The performance on linux are a bit slower than in Windows regarding that library. That being said, it works ;).
