### ISSUE TITLE
Where Can I get the source code for V 2.0.0?

### ISSUE THREAD

**Issue by DeeDeeLee** [Nordes/IdentityServer4.LdapExtension#25]
I am try to use IdentityServer4.LdapExtension with the IdentityServer4 v.2.2.0.  I was told that I must use IdentityServer4.LdapExtension v.2.0.0. Where can I download the source code for V 2.0.0? Is there way to make IdentityServer4.LdapExtension V.2.1.7 work with IdentityServer4 V2.2.0?

**Comment by Nordes** [comment]
This is an extension made by myself and not by the official develop of the IdentityServer. Because of that my version numbers are not following the official ones. 

Regarding the version requirement, I am updating the package now to the latest version and it should be available soon.

**Comment by Nordes** [comment]
Regarding the download of prior version, you can simply look in the history of the commits.

The Nuget package is available on nuget.org: https://www.nuget.org/packages/IdentityServer.LdapExtension/2.0.0
---
Regarding which version of the package match which version of ID4, it's hard to tell you which is which. But I would recommend you to update to the latest version of everything.
