### ISSUE TITLE
What is possible with implementation of ILDAP User store?

### ISSUE THREAD

**Issue by chazt3n** [Nordes/IdentityServer4.LdapExtension#28]
same as title, just curious what the intention is of that

**Comment by jronnen7** [comment]
There are a very few cases where you might find it worth while to implement this.  In general, the built in implementations for Redis or InMemory work great.  I would imagine it would make sense to implement these layers when some other shared caching service (other than redis) is used when load balancing.

The only other time it is worth implementing is when your `subject_id` is going to differ from your `username`, in general this should never happen, but I recently had a case where this was true.  The application allowed superusers to login as other users and view the application from their point of view for better debugging.  Such a use case required the implementation as it was causing bugs matching on subject_id vs username, if you look at the default implementations you will see what I mean, but in general you shouldn't have to worry about any added functionality by implementing the user store.
