### ISSUE TITLE
Throws an error if UID attribute is not present in Active Directory

### ISSUE THREAD

**Issue by abhisheknaik07** [Nordes/IdentityServer4.LdapExtension#29]
If UID attribute is not present in active directory, below line throws an error as it doesn't find username.

https://github.com/Nordes/IdentityServer4.LdapExtension/blob/7447e522ab34b37feb518635587b153a42dba59a/IdentityServer.LdapExtension/UserModel/ActiveDirectoryAppUser.cs#L131

**Comment by Nordes** [comment]
There's no magic ;). Usually I would say that you are supposed to know which attributes you have in your AD. That being said, the "username" is a normal attribute in a normal AD. If you are using OpenLdap, it may differ (based on schema).
