### ISSUE TITLE
Education videosu

### ISSUE THREAD

**Issue by murattdogan** [Nordes/IdentityServer4.LdapExtension#3]
Hello Do you know how to use the package with a video. For beginners like me, we can learn more easily and more easily.

**Comment by Nordes** [comment]
Hi @murat0058 ,

I'll try to do that. For now I am quite busy :). Have you looked at the article? If yes, tell me which point you are struggling.

**Comment by murattdogan** [comment]
If you add this project to my project, I would like to join and develop myself in the active directory part

**Comment by murattdogan** [comment]
I add you whatsApp

**Comment by murattdogan** [comment]
+90 545 858 25 58 whatsap

**Comment by Nordes** [comment]
I will close this issue. A solution to your issue have been given in the #10
