### ISSUE TITLE
**401 Unauthorized** all the time 

### ISSUE THREAD

**Issue by rayovims** [Nordes/IdentityServer4.LdapExtension#31]
I keep on trying to login with a user that is already in our active directory, but it seems it can't find it? I don't know if the connection is the problem or what because there are no errors stating error with the connection. I am using ActiveDirectoryAppUser instead of the OpenLDAP one. I know this is kind of broad but, the problem seems to not lead me to anything specific. I don't know if I am missing something. When I debug it gets to the part of validatingCredentials in the "inMemoryUserStore.cs" file (I downloaded the source code and added it to my solution in order to debug). It gets the correct credentials that are passed by thru postman. Once it trys to use the "_authenticationService.login(username, password)" method I don't know what happens but the user is unauthorized. 

**this is the validateCredentials method** that is included in the ldapExtension project
--------------------------------------
public IAppUser ValidateCredentials(string username, string password)
        {
            try
            {
                var user = _authenticationService.Login(username, password);
                if (user != null)
                {
                    return user;
                }
            }
            catch (LoginFailedException)
            {
                return default(TUser);
            }

            return default(TUser);
        }

-------------------------------------------
**this is my login controller that is getting the data from postman**
-----------------------------------
[HttpPost("SignIn")]
        public async Task<IActionResult> SignIn([FromBody]LdapUser model)
        {
            // validate username/password against Ldap
            var user = userStore.ValidateCredentials(model.Username, model.Password);

            if (user != default(IAppUser))
            {
                // Response with authentication cookie
                await HttpContext.SignInAsync(user.SubjectId, user.Username);

                var token = await tools.IssueClientJwtAsync(
                   clientId: "MyBackend",
                   lifetime: 3600,
                   audiences: new[] { "MyBackend1", "MyBackend2" });

                // Get the Access token
                //var accessToken = await this.tools.IssueClientJwtAsync(lifetime: 3600, claims: new Claim[] { new Claim(JwtClaimTypes.Audience, model.ApiResource) });

                // Write the Access token to response
                await HttpContext.Response.WriteAsync(token);

                return Ok();
            }
            else
            {
                return Unauthorized();
            }
        }
------------------------------------------------------
**this is my startup file**
--------------------------------------------------------
public Startup(IConfiguration configuration)
        {
            this.Configuration = configuration;
        }
        public IConfiguration Configuration { get; }
     
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<IISOptions>(iis =>
            {
                iis.AuthenticationDisplayName = "Windows";
                iis.AutomaticAuthentication = false;
            });

            String sHostname = System.Net.Dns.GetHostName();

            services.AddMvc();

            services.AddIdentityServer()
                .AddDeveloperSigningCredential(persistKey: false)
                .AddInMemoryIdentityResources(Config.GetIdentityResources())
                .AddInMemoryApiResources(Config.GetAllApiResources())
                .AddInMemoryClients(Config.GetClients())
                .AddTestUsers(Config.GetUser())
                .AddLdapUsers<ActiveDirectoryAppUser>(this.Configuration.GetSection("LdapServer"), UserStore.InMemory);
            ;
        }
---------------------------------------------------

**I am also following this [guide](https://karatejb.blogspot.com/2019/07/aspnet-core-identity-server-4-ldap.html)** 

**Thank you for your time!**

**Comment by rayovims** [comment]
Turns out I had a O insted of a D for BindDn. I had BindOn... SMH. developer problems haha

**Comment by Nordes** [comment]
Sorry for late reply, thank you for the update.
