### ISSUE TITLE
groups/roles support

### ISSUE THREAD

**Issue by chrgraefe** [Nordes/IdentityServer4.LdapExtension#44]
Hi,

I'm using the LdapExtension with the AD flavour.
Are groups/roles supported yet?

I can't get it working. The authentication process is working well.

Is there anything I've to configure in advanced?

**Comment by chrgraefe** [comment]
Okay, I found it myself.

Just add

`services.AddScoped<IProfileService, LdapUserProfileService<ActiveDirectoryAppUser>>();`

in ConfigureServices method in Startup.cs

**Comment by gentilegianluca** [comment]
Hi, I try with `services.AddScoped<IProfileService, LdapUserProfileService<ActiveDirectoryAppUser>>();` but not work.
I need a role for each group the user belongs to.
Thanks for help.
