### ISSUE TITLE
Roadmap for support auf IdentityServer4 version 3.1.x and up

### ISSUE THREAD

**Issue by chrgraefe** [Nordes/IdentityServer4.LdapExtension#48]
Hi,

I want suggest an approach for going ahead for the next upgrade to an actual version of IdentityServer4.
IdentityServer4 version greater than 3.0.0 aren't supporting .NETStandard 2.0 any more.
You have to use TFM netcoreapp3.0 or netcoreapp3.1

What is your thought about branching the cuurent master into a maintenance branch for versions 2.1.x
Afterwards master we coud do the neccesseary changes for going ahead with new supported TFM like netcoreapp3.1.

any thoughts?

**Comment by Nordes** [comment]
Please see issue #65 , I've created a branch for 4.1.2 based on .Net 5.0. That being said, it's not yet published.

Ref for the branch: https://github.com/Nordes/IdentityServer4.LdapExtension/issues/65#issuecomment-818319239 (you can build the nuget package for now locally, I will try to build it this week)
