### ISSUE TITLE
Redirect back to client doesn't work.

### ISSUE THREAD

**Issue by DeeDeeLee** [Nordes/IdentityServer4.LdapExtension#6]
Hello,

I have down loaded your code and got it compiled. When I try to run the "MvcClient" with the "QuickstartIdentityServer", it wouldn't redirect me back to the "MvcClient" after I login. I traced it, it looks like the function "FindBySubjectId" always return me null. Any ideas?

Best Regards,
D. L.

**Comment by Nordes** [comment]
Hi D.L.,

have you configured properly your app settings? There's an another issue that someone raised about it. The issue mainly happened because of a miss configuration.

**Comment by DeeDeeLee** [comment]
Hi Nordes,

My app setting is fine. The problem is caused by AD attributes mismatch. Our AD doesn't support "uid" attribute.


Thank you so much for your replying,
D.L.
