### ISSUE TITLE
Low performance (in 100 times more) Connect/Bind methods in Docker on Win11 with Linux containers

### ISSUE THREAD

**Issue by P9avel** [Nordes/IdentityServer4.LdapExtension#77]
Hi, i am found bug https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/216
Possible you have background solution for this issue?

**Comment by Nordes** [comment]
No, sorry, I don't. 

Note that I did not really update the lib in quite a while. 

This lib was first created to be cross-platform (mainly Linux or WSL2 + windows). The windows part would be to develop, while the Linux would be more for production. I would expect your project to deploy within a production Kubernetes cluster and if it's the case, the best remains in Linux, not Windows. 

That said, if you want, you can also rewrite part of this to use the Microsoft lib to interact with the Ldap. At the beginning of this project was meant to show that it was possible to make an easy plugin to interface with Ldap + Identity Server 4.
