### ISSUE TITLE
ActiveDirectoryLdapAttributes and OpenLdapAttributes

### ISSUE THREAD

**Issue by murattdogan** [Nordes/IdentityServer4.LdapExtension#8]
ActiveDirectoryLdapAttributes and OpenLdapAttributes  one LdapAttributes.cs merge ?

**Comment by Nordes** [comment]
No, it can't. Both of them are for different type of server. OpenLdap is a LDAP server available (free). While the Ldap is the common windows server LDAP type.

Know that you can build your own LdapAttributes class if you use specific attributes within LDAP or if you have, let say, samba, which will have different attribute name.
